Controllers/IssuesController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using IssueTracker.Models;
using IssueTracker.Utils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;

namespace IssueTracker.Controllers
{
    public class IssuesController : Controller
    {
        private readonly IssueTrackerContext _context;
        private readonly INotyfService _notyf;

        public IssuesController(IssueTrackerContext context, INotyfService notyf)
        {
            _notyf = notyf;
            _context = context;
        }
        private Boolean IsNotLogged()
        {
            int? id = HttpContext.Session.GetInt32("UserId");

            return id == null || id < 0;
        }

        public async Task<IActionResult> Index(string searchString, string sortOrder, string sortType, 
            IssueStatus state, IssuePriority priority, int pageNumber = 1, int projectId = -1)
        {
            if (IsNotLogged())
            {
                return RedirectToAction("Index", "Authorization");
            }
            var userId = HttpContext.Session.GetInt32("UserId") ?? -1;

            var personProjectsIds = projectId < 0 ? 
                _context?.PersonProjects?.Where(p => p.PersonId == userId).Select(p => p.ProjectId) : 
                _context?.PersonProjects?.Where(p => p.PersonId == userId && p.ProjectId == projectId).Select(p => p.ProjectId);

            var issues = from m in _context?.Issues?.Where(i => personProjectsIds.Contains(i.ProjectId))
                .Include(i => i.Creator)
                .Include(i => i.Project) select m;

            foreach (var issue in issues)
            {
                issue.Asignee = _context?.PersonProjects?
                    .Where(p => p.ProjectId == issue.ProjectId && p.PersonId == issue.AsigneeId)?
                    .Select(p => p.Person)?
                    .FirstOrDefault();
            }
            
            if (!string.IsNullOrEmpty(searchString))
            {
                issues = issues.Where(i => i.Summary.ToLower().Contains(searchString.ToLower()));
            }

            ViewData["SummarySort"] = String.IsNullOrEmpty(sortOrder) ? "SummaryDesc" : "";
            ViewData["ProjectSort"] = sortOrder == "ProjectSort" ? "ProjectDesc" : "ProjectSort";
            ViewData["StateSort"] = sortOrder == "StateSort" ? "StateDesc" : "StateSort";
            ViewData["PrioritySort"] = sortOrder == "PrioritySort" ? "PriorityDesc" : "PrioritySort";

            issues = Utils.Issues.IssueSorts.sortByOrder(issues, sortOrder);

            ViewData["MyIssues"] = String.IsNullOrEmpty(sortType) ? "MyIssues" : "";
            ViewData["Priority"] = sortType != "Priority" ? "Priority" : "Priority";
            ViewData["State"] = sortType != "State" ? "State" : "State";

            issues = Utils.Issues.IssueSorts.sortByType(issues, sortType, state, priority, userId);

            return View(PaginatedList<Issue>.Create(issues, pageNumber, 8));
        }

        // GET
        public IActionResult Create()
        {
            if (IsNotLogged())
            {
                return RedirectToAction("Index", "Authorization");
            }

            var userId = GetUserId();

            var projects = _context.GetUserProjects(userId);
        
            ViewData["ProjectId"] = new SelectList(projects, "ProjectId", "Name");

            return View();
        }

        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Issue issue)
        {
            if (IsNotLogged())
            {
                return RedirectToAction("Index", "Authorization");
            }

            var userId = GetUserId();
            var creator = _context?.Persons?.FirstOrDefault(p => p.PersonId == userId);

            issue.CreatedOn = DateTime.Now;
            issue.CreatorId = userId;
            issue.State = IssueStatus.New;
            issue.Creator = creator;

            _context?.Add(issue);
            _context?.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult Details(int id, IssueDetails issueDetails)
        {
            if (IsNotLogged())
            {
                return RedirectToAction("Index", "Authorization");
            }

            var issue = _context?.Issues?.FirstOrDefault(i => i.Id == id);

            if (issue == null)
            {
                _notyf.Error("Issue not found");
                return RedirectToAction(nameof(Index));
            }

            issue.Asignee = _context?.Persons?.FirstOrDefault(p => p.PersonId == issue.AsigneeId);
            issue.Creator = _context?.Persons?.FirstOrDefault(p => p.PersonId == issue.CreatorId);

            var personProjects = _context?.PersonProjects?.Where(proj => proj.ProjectId == issue.ProjectId).ToList();
            var comments = _context?.Comments?.Where(c => c.IssueId == issue.Id).OrderByDescending(c => c.EditedOn).ToList();

            foreach (var pp in personProjects)
            {
                pp.Person = _context?.Persons?.FirstOrDefault(p => p.PersonId == pp.PersonId);
            }

            var userId = GetUserId();

            issueDetails.issue = issue;
            issueDetails.personProjects = personProjects;
            issueDetails.currentUser = _context?.Persons?.FirstOrDefault(p => p.PersonId == userId);
            issueDetails.comments = comments;
            issueDetails.userRole = _context.PersonProjects.Where(proj => proj.ProjectId == issue.ProjectId && proj.PersonId == userId)
                .Select(pers => pers.Role)
                .SingleOrDefault();
            
            return View(issueDetails);
        }



        // GET: Issue/Edit
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                _notyf.Error("Invalid action");
                return RedirectToAction("Index");
            }

            if (IsNotLogged())
            {
                return RedirectToAction("Index", "Authorization");
            }

            var issue = await _context.Issues.FindAsync(id);
            if (issue == null)
            {
                _notyf.Error("Issue not found");
                return RedirectToAction("Index");
            }

            var userId = HttpContext.Session.GetInt32("UserId") ?? -1;

            if (userId != issue.AsigneeId && userId != issue.CreatorId)
            {
                _notyf.Error("You cannot edit this issue");
                return RedirectToAction("Index");
            }

            ViewBag.MyStatesEnum = ConvertToEnum("states");
            ViewBag.MyPrioritiesEnum = ConvertToEnum("priority");

            return View(issue);
        }

        // POST: Issue/Edit
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditPost(int? id)
        {
            if (id == null)
            {
                _notyf.Error("Issue does not exist");
                return RedirectToAction(nameof(Index));
            }
            var issue = await _context.Issues.FirstOrDefaultAsync(p => p.Id == id);

            if (issue == null)
            {
                _notyf.Error("Issue does not exist");
                return RedirectToAction(nameof(Index));
            }

            if (await TryUpdateModelAsync<Issue>(
                issue,
                "",
                i => i.Summary, i => i.State, i => i.Priority, i => i.TargetResolutionDate, i => i.ActualResolutionDate, i => i.Description))
            {
                
                try
                {
                    await _context.SaveChangesAsync();
                    _notyf.Success("Issue successfuly edited");
                    return RedirectToAction("Details", new {id = issue.Id});
                }
                catch (DbUpdateException)
                {
                    ModelState.AddModelError("", "Unable to save changes. " +
                        "Try again, and if the problem persists, " +
                        "see your system administrator.");
                }
            }
            return View(issue);
        }

        // POST: Issues
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            var issue = _context.Issues.Find(id);
            _context.Issues.Remove(issue);
            _context.SaveChanges();

            _notyf.Success("Issue successfuly deleted");
            return RedirectToAction(nameof(Index));
        }

        private List<ConvertEnum> ConvertToEnum(string type)
        {
            var myStates = new List<ConvertEnum>();
            
            if (type == "priority")
            {
                foreach (IssuePriority priority in Enum.GetValues(typeof(IssuePriority)))
                    myStates.Add(new ConvertEnum
                    {
                        Value = (int) priority,
                        Text = priority.ToString()
                    });
            } else
            {
                foreach (IssueStatus status in Enum.GetValues(typeof(IssueStatus)))
                    myStates.Add(new ConvertEnum
                    {
                        Value = (int) status,
                        Text = status.ToString()
                    });
            }
            
            return myStates;
        }
        
        public IActionResult AssignPerson(string email, int id)
        {
            if (IsNotLogged())
            {
                return RedirectToAction("Index", "Authorization");
            }

            var issue = _context?.Issues?.FirstOrDefault(i => i.Id == id);


            if (issue == null)
            {
                _notyf.Error("Issue not found");
                return RedirectToAction(nameof(Index));
            }

Controllers/PersonsController.cs
#nullable disable
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using IssueTracker.Models;
using AspNetCoreHero.ToastNotification.Abstractions;

namespace IssueTracker.Controllers
{
    public class PersonsController : Controller
    {
        private readonly IssueTrackerContext _context;
        private readonly INotyfService _notyf;

        public PersonsController(IssueTrackerContext context, INotyfService notyf)
        {
            _context = context;
            _notyf = notyf;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Profile()
        {
            int? id = HttpContext.Session.GetInt32("UserId");

            if (id == null)
            {
                _notyf.Error("You need to be logged in to view your profile.");
                return RedirectToAction("Index", "Authorization");
            }

            var person = _context.Persons
                .FirstOrDefault(p => p.PersonId == id);
            
            if (person == null)
            {
                _notyf.Error("Person not found.");
                return RedirectToAction("Index", "Authorization");
            }

            return View("Index", person);
        }

        // GET: Persons/Edit
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                _notyf.Error("You need to be logged in to edit your profile.");
                return RedirectToAction("Index", "Authorization");
            }

            int? userId = HttpContext.Session.GetInt32("UserId");
            if (id != userId)
            {
                _notyf.Error("Access denied.");
                return RedirectToAction("Profile");
            }

            var person = await _context.Persons
                .FindAsync(id);
            
            if (person == null)
            {
                _notyf.Error("Person not found.");
                return RedirectToAction("Index", "Authorization");
            }
            
            return View(person);
        }

        // POST: Persons/Edit
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditPost(int? id)
        {
            if (id == null)
            {
                _notyf.Error("You need to be logged in to edit your profile.");
                return RedirectToAction("Index", "Authorization");
            }

            int? userId = HttpContext.Session.GetInt32("UserId");
            if (id != userId)
            {
                _notyf.Error("Access denied.");
                return RedirectToAction("Profile");
            }

            var personToUpdate = await _context.Persons
                .FirstOrDefaultAsync(p => p.PersonId == id);

            // Update only the changed fields
            if (await TryUpdateModelAsync<Person>(
                personToUpdate,
                "",
                p => p.FirstName, p => p.SecondName))
            {
                try
                {
                    await _context.SaveChangesAsync();
                    
                    _notyf.Success("Profile updated successfully");
                    return RedirectToAction(nameof(Profile));
                }
                catch (DbUpdateException)
                {
                    ModelState.AddModelError("", "Unable to save changes. " +
                        "Try again, and if the problem persists, " +
                        "see your system administrator.");
                }
            }

            _notyf.Error("Updating profile failed");
            return View(personToUpdate);
        }
        
        // POST: Persons/Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            var user = _context.Persons
                .Find(id);
            
            _context.Persons.Remove(user);
            _context.SaveChanges();

            _notyf.Success("Account deleted");
            return RedirectToAction("Index", "Authorization");
        }

    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor httpContextAccessor;

<!DOCTYPE html>
<html lang="en" style="max-height:100vh">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IssueTracker</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/IssueTracker.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        .is-active {
            background-color: #a6a6a6;
            color: white!important;
        }
        .is-active:hover {
            background-color: #a6a6a6;
            color: black !important;
        }
        .btn-primary {
            background-color: #1c9954!important;
            border-color: #1c9954!important;
        }
    </style>
</head>
<body>
    
    <div class="d-flex" style="min-height:90vh">
        <div class="border-end bg-white">
            <div class="sidebar-heading border-bottom">
                <a asp-area="" asp-controller="Projects" asp-action="Index"><img class="p-2" style="width:10vw" alt=logo src=~/img/logo_side.png></a>
            </div>
            <div class="list-group list-group-flush menu-item">
                <a class="list-group-item list-group-item-action text-dark" asp-area="" asp-controller="Projects" asp-action="Index">Projects</a>
                <a class="list-group-item list-group-item-action text-dark" asp-area="" asp-controller="Issues" asp-action="Index">Issues</a>
                <a class="list-group-item list-group-item-action text-dark" asp-area="" asp-controller="Persons" asp-action="Profile">Profile</a>
            </div>
        </div>
        <div class="container">
            <nav class="navbar navbar-expand-lg navbar-light">
                <div class="container-fluid">
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ms-auto mt-2 mt-lg-0">
                            @if (@httpContextAccessor?.HttpContext?.Session.GetInt32("UserId") != null) {
                                <li class="nav-item active"><a class="nav-link text-dark" asp-area="" asp-controller="Authorization" asp-action="Logout"><i class="fa fa-sign-out" aria-hidden="true"></i>Logout</a></li>
                            } else
                            {
                                <li class="nav-item active"><a class="nav-link text-dark" asp-area="" asp-controller="Authorization" asp-action="Index">Login</a></li>
                                <li class="nav-item active"><a class="nav-link text-dark" asp-area="" asp-controller="Authorization" asp-action="Register">Register</a></li>
                            }
                        </ul>
                    </div>
                </div>
            </nav>

            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
        
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - IssueTracker
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script>
        (function () {
            let current = location.pathname.split('/')[1];
            if (current === "") return;
            let menuItems = document.querySelectorAll('.menu-item a');
            for (let i = 0, len = menuItems.length; i < len; i++) {
                if (menuItems[i].getAttribute("href").indexOf(current) !== -1) {
                    menuItems[i].className += " is-active";
                }
            }
        })();
    </script>    
    
    @await RenderSectionAsync("Scripts", required: false)
    @await Component.InvokeAsync("Notyf")
</body>
</html>

Views/Shared/_LayoutHome.cshtml
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor httpContextAccessor;

<!DOCTYPE html>
<html lang="en" style="max-height:100vh">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IssueTracker</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/IssueTracker.styles.css" asp-append-version="true" />
</head>
<body>
    
    <div class="d-flex" style="height:90vh">
        <div class="container">
            <nav class="navbar navbar-expand-lg navbar-light">
                <div class="container-fluid">
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ms-auto mt-2 mt-lg-0">
                            @if (@httpContextAccessor?.HttpContext?.Session.GetString("UserId") != null) {
                                <li class="nav-item active"><a class="nav-link text-dark" asp-area="" asp-controller="Authorization" asp-action="Logout">Logout</a></li>
                            } else
                            {
                                <li class="nav-item active"><a class="nav-link text-dark" asp-area="" asp-controller="Authorization" asp-action="Index">Login</a></li>
                                <li class="nav-item active"><a class="nav-link text-dark" asp-area="" asp-controller="Authorization" asp-action="Register">Register</a></li>
                            }
                        </ul>
                    </div>
                </div>
            </nav>

            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
        
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - IssueTracker
        </div>
    </footer>
    
        

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @await Component.InvokeAsync("Notyf")
</body>
</html>